/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;


import javax.swing.ImageIcon;
import classes.Calculadora;

/**
 *
 * @author rfrog
 */
public class JFrameCalculadora extends javax.swing.JFrame {
    
    float valor1, valor2;
    //InputStream is = JFrameCalculadora.class.getResourceAsStream("/fontawesome-webfont.ttf");
    
    Operacao operacao;   
    Calculadora Calc = new Calculadora();            
    
    public static enum Operacao {
        Soma(1), Subtracao(2), Multiplicacao(4), Divisao(5), Porcento(6), Raiz(3), Quadrado(7);
        private final int codigo;

        Operacao(int codigo) { this.codigo = codigo; }

        int codigo() { return codigo; }

        public static Operacao porCodigo(int codigo) {
            for (Operacao op: Operacao.values()) {
                if (codigo == op.codigo()) return op;
            }
            throw new IllegalArgumentException("Operação inválida!");
        }
    }

    /**
     * Creates new form JFrameCalculadora
     */
    public JFrameCalculadora() {
        initComponents();
        this.setIconImage(new ImageIcon("calculator.png").getImage());
        
//                        String nome = null;
//                        int resposta;
//                        nome = JOptionPane.showInputDialog("Qual é o seu nome?");
//                        resposta = JOptionPane.showConfirmDialog(null, "O seu nome é " + nome + "?");
//                        if (resposta == JOptionPane.YES_OPTION) {
//                        // verifica se o usuário clicou no botão YES
//                          JOptionPane.showMessageDialog(null, "Seu nome é " + nome);
//                        } else {
//                          JOptionPane.showMessageDialog(null, "Seu nome não é " + nome);
//                        }
        
//        try (InputStream is = JFrameCalculadora.class.getResourceAsStream("fontawesome-webfont.ttf")) {
//                    Font font = Font.createFont(Font.TRUETYPE_FONT, is);
//                    //font = font.deriveFont(Font.PLAIN, 24f);
//
////                    JLabel label = new JLabel("?");
////                    label.setFont(font);
////
////                    JFrame frame = new JFrame("Testing");
////                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
////                    frame.setLayout(new GridBagLayout());
////                    frame.add(label);
////                    frame.pack();
////                    frame.setLocationRelativeTo(null);
////                    frame.setVisible(true);
//                      
////                        String nome = null;
////                        int resposta;
////                        nome = JOptionPane.showInputDialog("Qual é o seu nome?");
////                        resposta = JOptionPane.showConfirmDialog(null, "O seu nome é " + nome + "?");
////                        if (resposta == JOptionPane.YES_OPTION) {
////                        // verifica se o usuário clicou no botão YES
////                          JOptionPane.showMessageDialog(null, "Seu nome é " + nome);
////                        } else {
////                          JOptionPane.showMessageDialog(null, "Seu nome não é " + nome);
////                        }
//
//                    
//                } catch (IOException | FontFormatException exp) {
//                    exp.printStackTrace();
//                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldVisor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButtonMaisMenos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonVirgula = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButton1Div = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonMais = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonCE = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonDEL = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonPorcento = new javax.swing.JButton();
        jButtonRaizQuadrada = new javax.swing.JButton();
        jButtonQuadrado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setIconImages(null);
        setResizable(false);

        jTextFieldVisor.setEditable(false);
        jTextFieldVisor.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jTextFieldVisor.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVisor.setText("0");

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton0.setBackground(new java.awt.Color(255, 255, 255));
        jButton0.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonMaisMenos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMaisMenos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonMaisMenos.setText("±");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonVirgula.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVirgula.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonVirgula.setText(",");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIgual.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButton1Div.setBackground(new java.awt.Color(255, 255, 255));
        jButton1Div.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton1Div.setText("1/x");

        jButtonMenos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMenos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonMais.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMais.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonMais.setText("+");
        jButtonMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMultiplicacao.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonMultiplicacao.setText("x");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonCE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCE.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonCE.setText("CE");

        jButtonC.setBackground(new java.awt.Color(255, 255, 255));
        jButtonC.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonDEL.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDEL.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonDEL.setText("DEL");
        jButtonDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELActionPerformed(evt);
            }
        });

        jButtonDivisao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDivisao.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonDivisao.setText("÷");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonPorcento.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPorcento.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonPorcento.setText("%");
        jButtonPorcento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorcentoActionPerformed(evt);
            }
        });

        jButtonRaizQuadrada.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRaizQuadrada.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonRaizQuadrada.setText("√");

        jButtonQuadrado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQuadrado.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButtonQuadrado.setText("x²");
        jButtonQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMais, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1Div, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRaizQuadrada)
                    .addComponent(jButtonQuadrado)
                    .addComponent(jButtonPorcento)
                    .addComponent(jButton1Div))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCE)
                    .addComponent(jButtonDEL)
                    .addComponent(jButtonDivisao)
                    .addComponent(jButtonC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMultiplicacao)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButtonMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButtonMais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMaisMenos)
                    .addComponent(jButton0)
                    .addComponent(jButtonVirgula)
                    .addComponent(jButtonIgual))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldVisor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    private void jButtonMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisActionPerformed
        if (jTextFieldVisor.getText().charAt(jTextFieldVisor.getText().length()-1) == '+')
            return;
        
        jTextFieldVisor.setText(jTextFieldVisor.getText() + "+");
    }//GEN-LAST:event_jButtonMaisActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonPorcentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPorcentoActionPerformed

    private void jButtonQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuadradoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "1" : jTextFieldVisor.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "0" : jTextFieldVisor.getText() + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "2" : jTextFieldVisor.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "3" : jTextFieldVisor.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "4" : jTextFieldVisor.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "5" : jTextFieldVisor.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "6" : jTextFieldVisor.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "7" : jTextFieldVisor.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "8" : jTextFieldVisor.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextFieldVisor.setText(jTextFieldVisor.getText().equals("0") ? "9" : jTextFieldVisor.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELActionPerformed
        jTextFieldVisor.setText( jTextFieldVisor.getText().equals("0") || jTextFieldVisor.getText().equals("") ? "0" : jTextFieldVisor.getText().substring(0, jTextFieldVisor.getText().length()-1));
    }//GEN-LAST:event_jButtonDELActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
//        valor1 = Float.parseFloat(jTextFieldVisor.getText());
//        operacao = Operacao.Subtracao;
//        jTextFieldVisor.setText("0");

        if (jTextFieldVisor.getText().charAt(jTextFieldVisor.getText().length()-1) == '-')
            return;
        
        jTextFieldVisor.setText(jTextFieldVisor.getText() + "-");
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        Calc.calcular("+");
        valor2 = Float.parseFloat(jTextFieldVisor.getText());
        float resultado;
        
        if(operacao == null)
            return;
        
            switch(operacao){
                case Subtracao:
                    resultado = valor1 - valor2;
                    jTextFieldVisor.setText(String.valueOf(resultado));
                    break;
                case Soma:
                    resultado = valor1 + valor2;
                    jTextFieldVisor.setText(String.valueOf(resultado));
                    break;
                case Divisao:
                    resultado = valor1 / valor2;
                    jTextFieldVisor.setText(String.valueOf(resultado));
                    break;
                case Multiplicacao:
                    resultado = valor1 * valor2;
                    jTextFieldVisor.setText(String.valueOf(resultado));
                    break;
                case Quadrado:
                    resultado = (float) Math.sqrt(valor1);
                    jTextFieldVisor.setText(String.valueOf(resultado));
                    break; 
                default:
                    jTextFieldVisor.setText("0");
                    break;
        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Div;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButtonDEL;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMais;
    private javax.swing.JButton jButtonMaisMenos;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonPorcento;
    private javax.swing.JButton jButtonQuadrado;
    private javax.swing.JButton jButtonRaizQuadrada;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldVisor;
    // End of variables declaration//GEN-END:variables
}
